1.0/ennichi/ennichi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streetview.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

1.0/ennichi/streetview/urls.py
from django.urls import path

from . import views

app_name = 'streetview'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('view/', views.scene_view, name='view'),
    path('view/ajax/', views.ajax_transition, name='ajax_transition'),
]

1.0/ennichi/streetview/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import generic

from .models import Scene, RelatedScene

class HomeView(generic.TemplateView):
    template_name = 'streetview/home.html'


def scene_view(request):
    context = {}
    return render(request, 'streetview/view.html', context)


def ajax_transition(request):
    scene_id = request.GET.get('id')
    scene = Scene.objects.get(id=scene_id)
    scene_image_url = scene.image.url

    relatedscene_list = RelatedScene.objects.all().filter(parent_scene=scene)
    relatedscene_id = [relatedscene.scene_id for relatedscene in relatedscene_list]
    relatedscene_theta = [relatedscene.theta for relatedscene in relatedscene_list]

    d = {
        'scene_id': scene_id,
        'scene_image_url': scene_image_url,
        'relatedscene_id': relatedscene_id,
        'relatedscene_theta': relatedscene_theta,
    }
    return JsonResponse(d)

1.0/ennichi/streetview/templates/streetview/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <title>{% block title %}筑駒ストリートビュー{% endblock %}</title>
        <link rel='shortcut icon' href='{% static "streetview/images/favicon.png" %}' type='image/png'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='{% static "streetview/css/bootstrap.css" %}'>
        <link rel='stylesheet' href='{% static "streetview/css/style.css" %}'>
        <link href='https://use.fontawesome.com/releases/v5.6.1/css/all.css' rel='stylesheet'>
        <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
        <script src='{% static "streetview/js/aframe.min.js" %}'></script>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'
            integrity='sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49'
            crossorigin='anonymous'></script>
        <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'
            integrity='sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy'
            crossorigin='anonymous'></script>
        {% block content %}{% endblock %}
    </body>
</html>

1.0/ennichi/streetview/templates/streetview/home.html
{% extends 'streetview/base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
Home
{% endblock %}

1.0/ennichi/streetview/templates/streetview/view.html
{% extends "streetview/base.html" %}
{% load static %}
{% load app %}

{% block content %}
<script type="module">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
            var cookies = document.cookie.split(";");
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + "=")) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie("csrftoken");
    var prefnl;
    var predir = 0;

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });




    var scene, camera, renderer;
    var controls;
    var image_url = "./images/puydesancy.jpg";
    var sphere, cube;
    var clickTargets = [];
    var forwardButtonGroup = new THREE.Group();
    var relatedSceneId = [], relatedSceneTheta = [];

    class ForwardButton extends THREE.Mesh {
        constructor() {
            const geometry = new THREE.BoxGeometry();
            const material = new THREE.MeshNormalMaterial();
            super(geometry, material);
        }
    }

    window.addEventListener("resize", function() {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize( window.innerWidth, window.innerHeight );
    }, false);

    window.addEventListener("click", function(e) {
        var raycaster = new THREE.Raycaster();
        var mouse = new THREE.Vector2();

        if (e.target == renderer.domElement) {
            mouse.x = ( e.clientX / window.innerWidth ) * 2 - 1;
            mouse.y = - ( e.clientY / window.innerHeight ) * 2 + 1;

            raycaster.setFromCamera( mouse, camera );

            var obj = raycaster.intersectObjects( clickTargets );
            
            if ( obj.length > 0 ){
                $.ajax({
                    "url": "{% url 'streetview:ajax_transition' %}",
                    "type": "GET",
                    "data": {
                        "id": scene_id,
                    },
                    "dataType": "json",
                    "cache": false,
                }).done( r => {
                    image_url = r.scene_image_url;
                    relatedSceneId = r.related_scene_id;
                    relatedSceneTheta = r.related_scene_theta;

                    initWorld();
                });
            }
        }
    });

    window.addEventListener("load", function() {
        init();
        checkDevice();
        initWorld();
    });

    function init() {
        scene = new THREE.Scene();
        camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 0.1, 1000 );
        camera.position.set( 1.5, 0, 0 );
        scene.add( camera );

        renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );            
        renderer.xr.enabled = true;
        
        document.body.appendChild( renderer.domElement );
    }

    function checkDevice(){
        if ("xr" in navigator) {
            navigator.xr.isSessionSupported("immersive-vr").then(function(supported) {
                if(supported) {
                    renderer.xr.enabled = true;
                } else {
                    setController();
                }
            })
        } else {
            setController();
        }
    }

    function setController() {
        document.addEventListener("touchmove", function(e) { e.preventDefault(); }, { passive:false });
        controls = new THREE.OrbitControls( camera, renderer.domElement );
        controls.target.set( 0, 0, 0 );
        controls.enableDamping = true;
        controls.dampingFactor = 0.5;
        controls.enableZoom = false;
    }

    function initWorld() {
        while(scene.children.length > 0){ 
            scene.remove( scene.children[0] ); 
        }

        const geometry = new THREE.SphereGeometry( 100, 100, 100 );
        geometry.scale( -1, 1, 1 );

        const texture = new THREE.TextureLoader().load( image_url );
        const material = new THREE.MeshBasicMaterial({
            map: texture
        });

        sphere = new THREE.Mesh( geometry, material );
        scene.add( sphere );

        initObjects();
    }

    function initObjects() {
        for (var i = 0; i < relatedSceneId.length; i++) {
            const mesh = new ForwardButton();

            const radian = relatedSceneTheta[i];
            mesh.position.set(
                8 * Math.cos(radian),
                3,
                8 * Math.sin(radian)
            );

            mesh.name = "forward_button_" + toString(i);
            clickTargets.push( mesh );

            forwardButtonGroup.add(mesh);
        }

        scene.add( forwardButtonGroup );

        rendering();
    }
    
    function rendering() {
        const animate = function() {
            if(controls){
                controls.update();
            }
            
            renderer.render( scene, camera );
            requestAnimationFrame( animate );
        };
        animate();
    }
</script>
{% endblock %}