streetview/geomap/urls.py
from django.urls import path

from . import views

app_name = 'geomap'

urlpatterns = [
    path('', views.geomap_view, name='index'),
]

streetview/scenes/urls.py
from django.urls import path

from . import views

app_name = 'scenes'

urlpatterns = [
    path('', views.scene_view, name='index'),
    path('ajax/', views.ajax_transition, name='ajax_transition'),
]

streetview/streetview/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scenes.urls')),
    path('geomap/', include('geomap.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

streetview/geomap/models.py
from django.db import models

streetview/scenes/models.py
from django.db import models


class Scene(models.Model):
    id = models.IntegerField('Id', primary_key=True)
    name = models.CharField('Name', max_length=30, default='', blank=True)
    image = models.ImageField('Image', upload_to='images/')

    def __str__(self):
        return str(self.id)


class RelatedScene(models.Model):
    parent_scene = models.ForeignKey(Scene, on_delete=models.CASCADE)
    scene_id = models.IntegerField('Scene Id', default=0)
    theta = models.FloatField('Button Rotation - Y', default=0.0)

streetview/geomap/views.py
from django.shortcuts import render


def geomap_view(request):
    context = {}
    return render(request, 'geomap/index.html', context)

streetview/scenes/views.py
from django.http import JsonResponse
from django.shortcuts import render

from .models import Scene, RelatedScene


def scene_view(request):
    context = {}
    return render(request, 'scenes/index.html', context)


def ajax_transition(request):
    scene_id = request.GET.get('id')
    scene = Scene.objects.get(id=scene_id)
    scene_image_url = scene.image.url

    relatedscene_list = RelatedScene.objects.all().filter(parent_scene=scene)
    relatedscene_id = [relatedscene.scene_id for relatedscene in relatedscene_list]
    relatedscene_theta = [relatedscene.theta for relatedscene in relatedscene_list]

    d = {
        'scene_id': scene_id,
        'scene_image_url': scene_image_url,
        'relatedscene_id': relatedscene_id,
        'relatedscene_theta': relatedscene_theta,
    }
    return JsonResponse(d)

streetview/scenes/templates/geomap/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}StreetView{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'geomap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'geomap/css/style.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <script src="{% static 'geomap/js/three.min.js' %}"></script>
        <script src="{% static 'geomap/js/OrbitControls.js' %}"></script>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
        {% block content %}{% endblock %}
    </body>
</html>

streetview/scenes/templates/geomap/index.html
{% extends "geomap/base.html" %}
{% load static %}

{% block content %}
<div id="status-window">
    <lable>Zoom Level:</lable>
    <input id="zoom-level" type="number" placeholder="5~14" value="14" min="5" max="14" step="1">
    <lable>Scale:</lable>
    <input id="change-scale" type="number" placeholder="-5~0" value="0" min="-5" max="0" step="1">
    <button id="get-location" type="button">Get Location</button>
</div>

<script type="module">

    document.getElementById( "zoom-level" ).addEventListener( "change", function(e) {

        zoomLevel = document.getElementById( "zoom-level" ).value;
        if ( zoomLevel > 14 ) zoomLevel = 14;
        if ( zoomLevel < 5 ) zoomLevel = 5;
        
        while(mapGroup.children.length > 0){ 
            mapGroup.remove( mapGroup.children[0] );
        }
        
        scene.remove( mapGroup );

        start();
        animate();
    });


    document.getElementById( "get-location" ).addEventListener( "click", function(e) {
        getLocation();
        start();
        animate();
    });


    document.getElementById( "change-scale" ).addEventListener( "change", function(e) {

        const ratio = Math.pow( 10, document.getElementById( "change-scale" ).value - scale );

        for ( let tileNum = 0; tileNum < mapGroup.children.length; tileNum++ ) {
            
            let vertices = mapGroup.children[ tileNum ].geometry.attributes.position.array;

            for ( let y = 0; y < TILE_SIZE - 1; y++ ) {
                for ( let x = 0; x < TILE_SIZE - 1; x++ ) {
                    for ( let i = 0; i < 2; i++ ) {
                        for ( let j = 0; j < 3; j++ ) {

                            vertices[ ((( y * ( TILE_SIZE - 1 ) + x ) * 2 + i ) * 3 + j) * 3 + 2 ] *= ratio;
                        }
                    }
                }
            }

            mapGroup.children[ tileNum ].geometry.attributes.position.needsUpdate = true;
        }

        scale = document.getElementById( "change-scale" ).value;
    });



    //three.js

    const TILE_SIZE = 256;
    const t = [
            { x: 0, y: 0 },
            { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 0, y: 1 }, { x: -1, y: 1 }, 
            { x: -1, y: 0 }, { x: -1, y: -1 }, { x: 0, y: -1 }, { x: 1, y: -1 },
            { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 2 }, { x: 1, y: 2 }, 
            { x: 0, y: 2 }, { x: -1, y: 2 }, { x: -2, y: 2 }, { x: -2, y: 1 },
            { x: -2, y: 0 }, { x: -2, y: -1 }, { x: -2, y: -2 }, { x: -1, y: -2 }, 
            { x: 0, y: -2 }, { x: 1, y: -2 }, { x: 2, y: -2 }, { x: 2, y: -1 },
        ];
    let zoomLevel = 14;

    let scene;
    let camera;
    let renderer;
    let controls;
    let mapDataList = new Array(9);
    let mapGroup = new THREE.Group();
    var location;
    let scale = 0;


    window.addEventListener("resize", function() {

        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();

        renderer.setSize( window.innerWidth, window.innerHeight );

    }, false);


    window.addEventListener("load", function() {
        init();
        start();
        animate();
    });


    function init() {

        scene = new THREE.Scene();

        camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 0.1, 10000 );
        camera.position.set(0, 1200, 0);
        camera.lookAt(0, 0, 0);
        scene.add( camera );

        renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );
        
        document.body.appendChild( renderer.domElement );

        zoomLevel = document.getElementById("zoom-level").value;
        console.log(zoomLevel);

        location = { latitude: 35.6851, longtitude: 139.7528 };

        setController();
    }


    function setController() {

        document.addEventListener("touchmove", function(e) { e.preventDefault(); }, { passive:false });

        controls = new THREE.OrbitControls( camera, renderer.domElement );

        controls.target.set( 0, 0, 0 );
        controls.enableDamping = true;
        controls.dampingFactor = 0.5;
        controls.enableZoom = true;
    }


    function getLocation() {

        navigator.geolocation.getCurrentPosition(function( position ) {
            const lat = position.coords.latitude;
            const lng = position.coords.longitude;
            location = { latitude: lat, longtitude: lng };
            console.log(location);
        });
    }


    function start() {

        while ( mapGroup.children.length > 0 ) { 
            mapGroup.remove( mapGroup.children[0] );
        }

        console.log(location);

        const tileCoordinate = getTileCoordinate( zoomLevel, location.latitude, location.longtitude );

        for(let i = 0; i < t.length; i++) {
            const x = parseInt( tileCoordinate.x ) + t[i].x;
            const y = parseInt( tileCoordinate.y ) + t[i].y;
            loadData( i, zoomLevel, x, y );
        }

        scene.add( mapGroup );
    }


    function getTileCoordinate( z, lat, lng ) {

        const L = 85.05112878;
        const pixelCoordinate = {
            x: TILE_SIZE * Math.pow(2, z) * ( ( lng + 180 ) / 360 ),
            y: TILE_SIZE * Math.pow(2, z) / ( 2 * Math.PI ) * ( - Math.atanh( Math.sin( Math.PI / 180 * lat )) + Math.atanh( Math.sin( Math.PI / 180 * L ) ) )
        };

        const tileCoordinate = {
            x: pixelCoordinate.x / TILE_SIZE,
            y: pixelCoordinate.y / TILE_SIZE
        };

        return tileCoordinate;
    }


    function loadData( tileNum, z, x, y ) {

        let req = new XMLHttpRequest();
        req.open( "GET", `https://cyberjapandata.gsi.go.jp/xyz/dem/${z}/${x}/${y}.txt` );
        req.send();
        	
        req.onload = function() {

            let row = req.responseText.split("\n");

            let mapData = new Array( TILE_SIZE );

            for(let i = 0; i < TILE_SIZE; i++) {
                mapData[i] = row[i].split(",");
            }
            
            const imageUrl = `https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/${z}/${x}/${y}.jpg`;

            drawMap( tileNum, mapData, imageUrl );
        }
    }


    function drawMap( tileNum, mapData, imageUrl ) {

        let geometry = new THREE.BufferGeometry();
        let vertices = [];
        let normals = [];
        let uvs = [];

        const dx = [[ 0, 1, 1 ], [ 0, 0, 1 ]], dy = [[ 0, 1, 0 ], [ 0, 1, 1 ]];

        // ((y * TILE_SIZE + x) * 2 + i) * 3 + j
        for(let y = 0; y < TILE_SIZE - 1; y++) {
            for(let x = 0; x < TILE_SIZE - 1; x++) {
                for(let i = 0; i < 2; i++) {
                    for(let j = 0; j < 3; j++) {

                        let z = mapData[ y + dy[i][j] ][ x + dx[i][j] ];
                        vertices.push( x + dx[i][j], y + dy[i][j], - z);
                        normals.push( 0, 0, 1 );
                        uvs.push( x / TILE_SIZE, 1 - y / TILE_SIZE );
                    }
                }
            }
        }

        geometry.setAttribute( "position", new THREE.Float32BufferAttribute( vertices, 3 ) );
        geometry.setAttribute( "normal", new THREE.Float32BufferAttribute( normals, 3 ) );
        geometry.setAttribute( "uv", new THREE.Float32BufferAttribute( uvs, 2 ) );
        geometry.computeVertexNormals ();

        const texture = new THREE.TextureLoader().load( imageUrl );
        const material = new THREE.MeshBasicMaterial({
            map: texture
        });

        const mesh = new THREE.Mesh( geometry, material );
        mesh.position.set( ( - 0.5 + t[tileNum].x ) * TILE_SIZE, 0, ( - 0.5 + t[tileNum].y ) * TILE_SIZE );
        mesh.rotation.set( 90 / 180 * Math.PI, 0, 0 );
        mesh.name = tileNum.toString();

        mapGroup.add( mesh );
    }

    function animate() {
        if ( controls ) {
            controls.update();
        }

        const c = { x: camera.position.x, y: camera.position.y, z: camera.position.z };

        renderer.render( scene, camera );
        requestAnimationFrame( animate );
    };

</script>
{% endblock %}

streetview/scenes/templates/scenes/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}StreetView{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'scenes/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'scenes/css/style.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <script src="{% static 'scenes/js/three.min.js' %}"></script>
        <script src="{% static 'scenes/js/OrbitControls.js' %}"></script>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
        {% block content %}{% endblock %}
    </body>
</html>

streetview/scenes/templates/scenes/index.html
{% extends "scenes/base.html" %}
{% load static %}

{% block content %}
<script type="module">

    const rotationOffset = 0 / 180 * Math.PI;
    let scene;
    let camera;
    let renderer;
    let controls;
    let imageUrl = "./images/puydesancy.jpg";
    let sphere;
    let clickTargets = [];
    let forwardButtonGroup = new THREE.Group();
    let sceneId;
    let relatedSceneId = [];
    let relatedSceneTheta = [];

    class ForwardButton extends THREE.Mesh {
        constructor() {
            const geometry = new THREE.CircleGeometry( 3, 32 );
            const material = new THREE.MeshBasicMaterial({
                map: new THREE.TextureLoader().load( "{% static 'scenes/images/forward.png' %}" )
            });
            super(geometry, material);
        }
    }


    window.addEventListener("resize", function() {

        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();

        renderer.setSize( window.innerWidth, window.innerHeight );
        
    }, false);


    window.addEventListener("load", function() {
        checkDevice();
        init();
    });


    window.addEventListener("click", function(e) {

        if (e.target == renderer.domElement) {

            let raycaster = new THREE.Raycaster();
            let mouse = new THREE.Vector2();

            mouse.x = ( e.clientX / window.innerWidth ) * 2 - 1;
            mouse.y = - ( e.clientY / window.innerHeight ) * 2 + 1;

            raycaster.setFromCamera( mouse, camera );

            const obj = raycaster.intersectObjects( clickTargets );
            
            if ( obj.length > 0 ){
                sceneId = parseInt(obj[0].object.name);
                ajaxTransition();
            }
        }
    });

    function ajaxTransition() {

        let req = new XMLHttpRequest();

        req.open( "GET", "{% url 'scenes:ajax_transition' %}" + "?id=" + sceneId.toString() );
        req.send();

        req.onreadystatechange = function() {

            if (req.readyState == 4 && req.status == 200) {

                imageUrl = JSON.parse(req.responseText).scene_image_url;
                relatedSceneId = JSON.parse(req.responseText).relatedscene_id;
                relatedSceneTheta = JSON.parse(req.responseText).relatedscene_theta;

                initWorld();
            }
        }
    }


    function checkDevice(){

        if ("xr" in navigator) {

            navigator.xr.isSessionSupported("immersive-vr").then(function(supported) {
                if(supported) {
                    renderer.xr.enabled = true;
                } else {
                    setController();
                }
            })
        } else {
            setController();
        }
    }

    function setController() {

        document.addEventListener("touchmove", function(e) { e.preventDefault(); }, { passive:false });

        controls = new THREE.OrbitControls( camera, renderer.domElement );

        controls.target.set( 0, 0, 0 );
        controls.enableDamping = true;
        controls.dampingFactor = 0.5;
        controls.enableZoom = true;
    }

    function init() {

        scene = new THREE.Scene();

        camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 0.1, 1000 );
        camera.position.set(
            - Math.cos( rotationOffset ),
            0,
            - Math.sin( rotationOffset )
        );
        scene.add( camera );

        renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );
        renderer.xr.enabled = true;
        
        document.body.appendChild( renderer.domElement );

        sceneId = 1;
        ajaxTransition();
    }

    function initWorld() {

        while(forwardButtonGroup.children.length > 0){ 
            forwardButtonGroup.remove( forwardButtonGroup.children[0] );
        }

        while(scene.children.length > 0){ 
            scene.remove( scene.children[0] );
        }


        const geometry = new THREE.SphereGeometry( 100, 100, 100 );
        geometry.scale( -1, 1, 1 );

        const texture = new THREE.TextureLoader().load( imageUrl );
        const material = new THREE.MeshBasicMaterial({
            map: texture
        });

        sphere = new THREE.Mesh( geometry, material );
        scene.add( sphere );

        initObjects();
    }

    function initObjects() {

        for (let i = 0; i < relatedSceneId.length; i++) {

            const mesh = new ForwardButton();

            const radian = relatedSceneTheta[i] / 180 * Math.PI + rotationOffset;

            mesh.position.set(
                15 * Math.cos( radian ),
                -5,
                15 * Math.sin( radian )
            );
            mesh.rotation.set(
                Math.PI / 2,
                Math.PI,
                Math.PI / 2 - radian
            );

            mesh.name = relatedSceneId[i].toString();
            
            clickTargets.push( mesh );

            forwardButtonGroup.add(mesh);
        }

        scene.add( forwardButtonGroup );

        animate();
    }
    
    function animate() {

        if(controls){
            controls.update();
        }
        
        renderer.render( scene, camera );
        requestAnimationFrame( animate );
    };

</script>
{% endblock %}

streetview/scenes/templates/streetview/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}StreetView{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'streetview/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'streetview/css/style.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <script src="{% static 'streetview/js/three.min.js' %}"></script>
        <script src="{% static 'streetview/js/OrbitControls.js' %}"></script>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
        {% block content %}{% endblock %}
    </body>
</html>

streetview/scenes/templates/streetview/view.html
{% extends "streetview/base.html" %}
{% load static %}

{% block content %}
<script type="module">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
            var cookies = document.cookie.split(";");
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + "=")) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie("csrftoken");
    var prefnl;
    var predir = 0;

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });




      
    const rotationOffset = 180 / 180 * Math.PI;
    var scene, camera, renderer;
    var controls;
    var imageUrl = "./images/puydesancy.jpg";
    var sphere, cube;
    var clickTargets = [];
    var forwardButtonGroup = new THREE.Group();
    var sceneId;
    var relatedSceneId = [], relatedSceneTheta = [];

    class ForwardButton extends THREE.Mesh {
        constructor() {
            const geometry = new THREE.BoxGeometry();
            const material = new THREE.MeshNormalMaterial();
            super(geometry, material);
        }
    }

    window.addEventListener("load", function() {
        checkDevice();
        init();
        ajaxTransition();
    });

    window.addEventListener("resize", function() {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize( window.innerWidth, window.innerHeight );
    }, false);

    window.addEventListener("click", function(e) {
        if (e.target == renderer.domElement) {
            var raycaster = new THREE.Raycaster();
            var mouse = new THREE.Vector2();

            mouse.x = ( e.clientX / window.innerWidth ) * 2 - 1;
            mouse.y = - ( e.clientY / window.innerHeight ) * 2 + 1;

            raycaster.setFromCamera( mouse, camera );

            var obj = raycaster.intersectObjects( clickTargets );
            
            if ( obj.length > 0 ){
                sceneId = parseInt(obj[0].object.name);
                ajaxTransition();
            }
        }
    });

    function ajaxTransition() {
        var req = new XMLHttpRequest();
        req.open( 'GET', "{% url 'streetview:ajax_transition' %}" + "?id=" + sceneId.toString() );
        req.send();

        req.onreadystatechange = function() {
            if (req.readyState == 4 && req.status == 200) {
                imageUrl = JSON.parse(req.responseText).scene_image_url;
                relatedSceneId = JSON.parse(req.responseText).relatedscene_id;
                relatedSceneTheta = JSON.parse(req.responseText).relatedscene_theta;

                initWorld();
            }
        }
    }


    function checkDevice(){
        if ("xr" in navigator) {
            navigator.xr.isSessionSupported("immersive-vr").then(function(supported) {
                if(supported) {
                    renderer.xr.enabled = true;
                } else {
                    setController();
                }
            })
        } else {
            setController();
        }
    }

    function setController() {
        document.addEventListener("touchmove", function(e) { e.preventDefault(); }, { passive:false });
        controls = new THREE.OrbitControls( camera, renderer.domElement );
        controls.target.set( 0, 0, 0 );
        controls.enableDamping = true;
        controls.dampingFactor = 0.5;
        controls.enableZoom = false;
    }

    function init() {
        scene = new THREE.Scene();
        camera = new THREE.PerspectiveCamera( 60, window.innerWidth / window.innerHeight, 0.1, 1000 );
        camera.position.set(
            - Math.cos( rotationOffset ),
            0,
            - Math.sin( rotationOffset )
        );
        scene.add( camera );

        renderer = new THREE.WebGLRenderer();
        renderer.setSize( window.innerWidth, window.innerHeight );            
        renderer.xr.enabled = true;
        
        document.body.appendChild( renderer.domElement );

        sceneId = 1;
        renderer.domElement.click();
    }

    function initWorld() {
        while(forwardButtonGroup.children.length > 0){ 
            forwardButtonGroup.remove( forwardButtonGroup.children[0] );
        }
        while(scene.children.length > 0){ 
            scene.remove( scene.children[0] );
        }

        const geometry = new THREE.SphereGeometry( 100, 100, 100 );
        geometry.scale( -1, 1, 1 );

        const texture = new THREE.TextureLoader().load( imageUrl );
        const material = new THREE.MeshBasicMaterial({
            map: texture
        });

        sphere = new THREE.Mesh( geometry, material );
        scene.add( sphere );

        initObjects();
    }

    function initObjects() {
        for (var i = 0; i < relatedSceneId.length; i++) {
            const mesh = new ForwardButton();

            const radian = relatedSceneTheta[i] / 180 * Math.PI + rotationOffset;
            mesh.position.set(
                8 * Math.cos( radian ),
                -2,
                8 * Math.sin( radian )
            );

            mesh.name = relatedSceneId[i].toString();
            clickTargets.push( mesh );

            forwardButtonGroup.add(mesh);
        }

        scene.add( forwardButtonGroup );

        rendering();
    }
    
    function rendering() {
        const animate = function() {
            if(controls){
                controls.update();
            }
            
            renderer.render( scene, camera );
            requestAnimationFrame( animate );
        };
        animate();
    }
</script>
{% endblock %}