0.0/ennichi/ennichi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('streetview.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

0.0/ennichi/streetview/urls.py
from django.urls import path

from . import views

app_name = 'streetview'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('view/', views.scene_view, name='view'),
    path('view/ajax/', views.ajax_transition, name='ajax_transition'),
]

0.0/ennichi/streetview/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone

import math


class Scene(models.Model):
    id = models.IntegerField('ID', primary_key=True)
    name = models.CharField('地名', max_length=30, default='', blank=True)
    image = models.ImageField('画像', upload_to='images/')
    default_direction = models.FloatField('画像の初期方向', default=0.0)  #視点を回転（前方0度時計回り）

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'シーン'
        verbose_name_plural = 'シーン'


class RelatedScene(models.Model):
    parent_scene = models.ForeignKey(Scene, on_delete=models.CASCADE)
    scene_id = models.IntegerField('シーンのID', default=0)
    direction = models.FloatField('画像の初期方向', default=0.0) #視点を回転（前方0度時計回り）
    r = models.FloatField(default=18.0)
    theta = models.FloatField(default=0.0) #ボタンを移動（前方0度時計回り）
    button_size = models.FloatField('ボタンのサイズ', default=5.0)


class Event(models.Model):
    scene = models.ForeignKey(Scene, on_delete=models.CASCADE, blank=True)
    hp_url = models.URLField('HPのURL', max_length=200, blank=True,)
    twitter_url = models.URLField('TwitterのURL', max_length=200, blank=True,)
    youtube_url = models.URLField('YoutubeのURL', max_length=200, blank=True,)
    group_name = models.CharField('団体名', max_length=50,)
    event_name = models.CharField('イベント名', max_length=50,)
    image = models.ImageField('画像', upload_to='images/')
    description = models.CharField('説明', max_length=1000, blank=True)
    r = models.FloatField(default=17.0)
    theta = models.FloatField(default=0.0)  #ボタンを移動（前方0度時計回り）

    def __str__(self):
        return self.event_name

    class Meta:
        verbose_name = 'イベント'
        verbose_name_plural = 'イベント'


class LiveEvent(models.Model):
    parent_event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None)
    name = models.CharField('ライブイベント名', max_length=50, default='')
    start_date = models.DateTimeField('開始日時', default=timezone.now)
    end_date = models.DateTimeField('終了日時', default=timezone.now)
    image = models.ImageField('画像', upload_to='images/')
    live_url = models.URLField('LiveのURL', max_length=200, blank=True,)

0.0/ennichi/streetview/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.views import generic

from .models import Scene, RelatedScene, Event, LiveEvent

class HomeView(generic.TemplateView):
    template_name = 'streetview/home.html'


def scene_view(request):
    live_event_list = LiveEvent.objects.filter(start_date__lte=timezone.now(), end_date__gte=timezone.now()).order_by('end_date')[:10]
    next_live_event_list = LiveEvent.objects.filter(start_date__gt=timezone.now()).order_by('start_date')[:3]

    context = {
        'live_event_list': live_event_list,
        'next_live_event_list': next_live_event_list,
    }
    return render(request, 'streetview/view.html', context)


def ajax_transition(request):
    scene_id = request.GET.get('id')
    scene = Scene.objects.get(id=scene_id)
    scene_name = scene.name
    default_direction = scene.default_direction
    scene_image_url = scene.image.url

    relatedscene_list = RelatedScene.objects.all().filter(parent_scene=scene)
    relatedscene_id = [relatedscene.scene_id for relatedscene in relatedscene_list]
    relatedscene_r = [relatedscene.r for relatedscene in relatedscene_list]
    relatedscene_theta = [relatedscene.theta for relatedscene in relatedscene_list]
    relatedscene_button_size = [relatedscene.button_size for relatedscene in relatedscene_list]

    prev_scene_theta = request.GET.get('theta')

    event_list = Event.objects.all().filter(scene=scene)
    event_r = [event.r for event in event_list]
    event_theta = [event.theta for event in event_list]
    event_image_url = [event.image.url for event in event_list]
    event_name = [event.event_name for event in event_list]
    event_group_name = [event.group_name for event in event_list]
    event_hp_url = [event.hp_url for event in event_list]
    event_twitter_url = [event.twitter_url for event in event_list]
    event_youtube_url = [event.youtube_url for event in event_list]

    d = {
        'scene_id': scene_id,
        'scene_name': scene_name,
        'default_direction': default_direction,
        'scene_image_url': scene_image_url,
        'relatedscene_id': relatedscene_id,
        'relatedscene_r': relatedscene_r,
        'relatedscene_theta': relatedscene_theta,
        'relatedscene_button_size': relatedscene_button_size,
        'prev_scene_theta': prev_scene_theta,
        'event_r': event_r,
        'event_theta': event_theta,
        'event_image_url': event_image_url,
        'event_name': event_name,
        'event_group_name': event_group_name,
        'event_image_url': event_image_url,
        'event_hp_url': event_hp_url,
        'event_twitter_url': event_twitter_url,
        'event_youtube_url': event_youtube_url,
    }
    return JsonResponse(d)

0.0/ennichi/streetview/templates/includes/readme.html
{% load static %}
{% load app %}

<div class='container my-4'>
    
</div>

0.0/ennichi/streetview/templates/streetview/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <title>{% block title %}筑駒ストリートビュー{% endblock %}</title>
        <link rel='shortcut icon' href='{% static "streetview/images/favicon.png" %}' type='image/png'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='{% static "streetview/css/bootstrap.css" %}'>
        <link rel='stylesheet' href='{% static "streetview/css/style.css" %}'>
        <link href='https://use.fontawesome.com/releases/v5.6.1/css/all.css' rel='stylesheet'>
        <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
        <script src='{% static "streetview/js/aframe.min.js" %}'></script>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src='https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js'
            integrity='sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49'
            crossorigin='anonymous'></script>
        <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'
            integrity='sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy'
            crossorigin='anonymous'></script>
        {% block content %}{% endblock %}
    </body>
</html>

0.0/ennichi/streetview/templates/streetview/home.html
{% extends 'streetview/base.html' %}
{% load static %}
{% load app %}

{% block title %}
筑駒ストリートビュー｜ホーム
{% endblock %}

{% block content %}
<div id='background'><div id='dark-box'>
    <div id='title'>
        <img class='col-lg-4 col-sm-6 col-8' src='{% static "streetview/images/title_logo.png" %}'><br><br>
        <p class='text-light' style='font-size:0.9rem'>はじめに<a id='readme-btn' class='text-warning' href='#readme' onclick='showReadme()'>こちら</a>をお読みください</p>
        <br>
        <a class='btn btn-outline-light' style='width: 125px;' href='{% url "streetview:view" %}?id=1100' role='button'>
            <h4>ENTER</h4> <i class='fas fa-street-view fa-lg'></i>
        </a>
    </div>
    <div class='container'>
        <ul id='nav' style='list-style:none;' class='float-sm-none'>
            <li id='nav' class='text-white col-6 px-0'>
                <p style='font-size: 0.8rem'>Made by</p><h5>筑駒縁日班</h5>
            </li>
            <li id='line' class='mx-2'><img style='height:50px;' src='{% static "streetview/images/line.png" %}'></li>
            <li id='nav' class='text-white col-5 px-0'>
                <p style='font-size: 0.8rem'>Made with</p><h5>Aframe</h5>
            </li>
        </ul>
        <script>
            function showReadme(){
                if ($('#readme')[0].style.display == 'none') {
                    $('#readme')[0].style.display = 'block';
                    $('#background')[0].style.display = 'none';
                }
                else {
                    $('#readme')[0].style.display = 'none';
                    $('#background')[0].style.display = 'block';
                }
            }
        </script>
    </div>
</div></div>
<div id='readme' style='display:none;'>
    <a class='text-dark' style='z-index: 10; right: 20px; position: fixed; top: 12px;' href='#' onclick='showReadme()'><i class="fas fa-2x fa-times"></i></a>
    {% include 'includes/readme.html' %}
</div>

{% endblock %}